import Head from "next/head"
import { useEffect } from "react"
import { AppProvider } from "../context/AppContext"
import AOS from "aos"
import "aos/dist/aos.css"
import "../styles/globals.css"
 
export default function App({ Component, pageProps }) {
  useEffect(() => {
    AOS.init({
      duration: 1000,
			once: false,
      offset: 350
    });
  }, [])

  return(
    <AppProvider>
      <Head>
        <title>FrioPolar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </AppProvider>
  )
}


