import { useEffect } from "react";
import Head from "next/head"
import '../styles/globals.css'
import AOS from "aos";
import "aos/dist/aos.css";
 
export default function App({ Component, pageProps }) {
  useEffect(() => {
    AOS.init({
      duration: 1000,
			once: false,
      offset: 350
    });
  }, []);
  return(
    <>
      <Head>
        <title>FrioPolar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}


